import { BANK, l, type Field, type Language } from './audit-bank.ts';
import { assess, requiredFields, usable, val, type IntakeState, type Verdict } from './audit-engine.ts';
import { PRODUCT_CATALOG } from './audit-product-catalog.ts';

export function buildFinalBrief(s: IntakeState, language: Language): string {
  const a = assess(s);
  const t = (ka: string, ru: string, en: string) => l(ka, ru, en)[language];
  const evidence = (fields: Field[]) => fields.filter((f) => usable(s, f)).map((f) => {
    const fact = s.facts[f]!;
    return `• [${fact.id}] “${fact.quote}”${fact.status === 'estimated' ? t(' — თქვენი შეფასება', ' — ваша оценка', ' — your estimate') : ''}`;
  }).join('\n');
  const findings: Record<Verdict, string> = {
    measurement_first: t('პირველი ნაბიჯი გაზომვის წესისა და წყაროს მონაცემების გამართვაა. მიღებული პასუხები ჯერ არ იძლევა სანდო საფუძველს AI-ით ოპტიმიზაციისთვის.', 'Первый шаг — наладить измерение и исходные данные. Ответы пока не дают надёжной основы для оптимизации с AI.', 'Start with measurement and source data. The answers do not yet establish a reliable basis for AI optimization.'),
    process_first: t('პირველ რიგში არსებული პროცესის ან ჩვეულებრივი ავტომატიზაციის შემოწმებას ვურჩევთ. AI-ის დამატებითი სარგებელი ჯერ დასამტკიცებელია.', 'Сначала стоит проверить изменение процесса или обычную автоматизацию. Дополнительная польза AI пока требует доказательств.', 'First test a process change or conventional automation. The additional benefit of AI still needs evidence.'),
    pilot: t('განმეორებადი სამუშაო, აღწერილი ზიანი და ტესტისთვის მზადყოფნა მცირე AI პილოტის საფუძველს ქმნის. რეალური ეფექტი ტესტმა უნდა აჩვენოს.', 'Повторяемая работа, описанные потери и готовность к проверке дают основание для небольшого AI-пилота. Реальный эффект предстоит измерить.', 'Repeatable work, reported impact and test readiness support a small AI pilot. Its actual benefit must be measured.'),
    prepare: t('ავტომატიზაციის შესაძლებლობა ჩანს, მაგრამ მონაცემების, პასუხისმგებელი პირის ან რისკის საკითხი ჯერ მოსაგვარებელია.', 'Возможность автоматизации просматривается, но сначала нужно решить вопрос данных, ответственного или риска.', 'There is an automation opportunity, but data, ownership or risk needs attention first.'),
    not_now: t('თქვენი პასუხების მიხედვით, ამ პროცესში ცალკე AI პროექტის პრიორიტეტი არ დასტურდება.', 'По вашим ответам приоритет отдельного AI-проекта для этого процесса не подтверждается.', 'Your answers do not support prioritizing a separate AI project for this process.'),
    insufficient: t('ინფორმაცია ჯერ არ არის საკმარისი მიზეზის ან შესაფერისი AI პროდუქტის დასადასტურებლად.', 'Информации пока недостаточно, чтобы подтвердить причину проблемы или подходящий AI-продукт.', 'There is not enough information to confirm the cause or a suitable AI product.'),
    scoped_discovery: t('ამოცანა სპეციფიკური ახალი სისტემის scope-ს ჰგავს. ჯერ საჭიროა ცალკე discovery, სანამ ფუნქციას, ვადას ან ფასს ვიტყვით.', 'Задача похожа на scope новой специализированной системы. Сначала нужен отдельный discovery — до обещаний функций, сроков или цены.', 'This looks like a bespoke new-system scope. A separate discovery is needed before functions, timing or price can be stated.'),
    technical_assessment: t('ეს უკვე არსებული აპლიკაციის ტექნიკური შეფასების ამოცანაა. Quick Audit არ ასრულებს code/security audit-ს და არ ითხოვს საიდუმლო წვდომას.', 'Это задача технической оценки уже существующего приложения. Quick Audit не выполняет code/security audit и не просит секретный доступ.', 'This is a technical assessment of an existing application. Quick Audit does not perform a code/security audit or request secret access.'),
    human_service: t('აქ ავტომატიზაციის ნაცვლად უფრო სწორი შეიძლება იყოს ცოცხალი სპეციალისტის ჩართვა. ეს არის მომსახურების hypothesis და არა AI-ის შედეგის დაპირება.', 'Здесь вместо автоматизации может быть уместнее подключение живого специалиста. Это гипотеза сервиса, а не обещание результата AI.', 'A live specialist may fit this better than automation. This is a service hypothesis, not a promised AI outcome.'),
    not_available: t('ეს მიმართულება ამ Quick Audit-ით ამჟამად არ ინერგება. სხვა ჩვეულებრივი ლოგისტიკური პროცესი შეიძლება ცალკე შეფასდეს.', 'Это направление сейчас не внедряется через Quick Audit. Обычный логистический процесс можно оценить отдельно.', 'This direction is not currently deployed through Quick Audit. A regular logistics process can be assessed separately.'),
  };
  let next = t('აირჩიეთ ამ პროცესის მცირე ნიმუში, გაზომეთ მიმდინარე შედეგი და ჩაიწერეთ შეცდომის მიზეზები.', 'Возьмите небольшую выборку процесса, измерьте текущий результат и запишите причины ошибок.', 'Take a small sample of the process, measure its current outcome and record causes of errors.');
  let metrics = t('სამუშაოს დრო, შეცდომები და დასრულებული შემთხვევები.', 'Время работы, ошибки и завершённые случаи.', 'Work time, errors and completed cases.');
  let caution = t('შედეგი შეამოწმოს ადამიანმა. დროის დაზოგვა ავტომატურად არ ნიშნავს ფულად ეკონომიას.', 'Результат проверяет человек. Высвобождение времени не равно денежной экономии.', 'A person should review results. Time released does not automatically mean cash savings.');
  let diagnosis = '';
  if (s.focus === 'attribution') {
    const gap = val(s, 'reporting_gap');
    diagnosis = ['none', 'ask'].includes(val(s, 'attribution')) || gap === 'missing'
      ? t('შეკვეთის წყაროს სანდო აღრიცხვა ჯერ არ დასტურდება. ეს ზღუდავს ინფლუენსერების შედარებას, თუმცა არ ამტკიცებს, რომ თავად კამპანია არაეფექტიანია.', 'Надёжная фиксация источника заказа пока не подтверждена. Это ограничивает сравнение блогеров, но не доказывает неэффективность самих кампаний.', 'Reliable order-source recording is not established. This limits comparisons between influencers, but does not prove that campaigns are ineffective.')
      : gap === 'manual' || gap === 'fragmented'
        ? t('თქვენ აღწერთ მონაცემების შეგროვებისა და შეჯერების სირთულეს. ჩვეულებრივი ინტეგრაცია ან ანგარიშის ავტომატიზაცია შესამოწმებელი ალტერნატივაა.', 'Вы описываете трудность сбора и сведения данных. Обычная интеграция или автоматизация отчёта — альтернатива, которую стоит проверить.', 'You describe difficulty collecting and reconciling data. Conventional integration or report automation is an alternative to test.') : '';
    next = a.verdict === 'measurement_first'
      ? t('ერთი მომდევნო კამპანიისთვის შეათანხმეთ წყაროს აღრიცხვის წესი. ტესტური შეკვეთით გადაამოწმეთ, ინახება თუ არა არჩეული ბმული ან კოდი შეკვეთასთან ერთად; უცნობი წყარო ცალკე დატოვეთ.', 'Для одной следующей кампании согласуйте правило учёта источника. Тестовым заказом проверьте сохранение выбранной ссылки или кода в заказе; неизвестный источник учитывайте отдельно.', 'For one upcoming campaign, agree a source-recording rule. Use a test order to verify that the chosen link or code is retained on the order; keep unknown sources separate.')
      : t('ერთი კამპანიის შეკვეთები, ხარჯი და წყაროს ჩანაწერები ერთ ცხრილში შეაჯერეთ. ჯერ გადაამოწმეთ ხელით, შემდეგ შეადარეთ ჩვეულებრივ ავტომატიზაციას.', 'Сведите заказы, расходы и записи об источнике одной кампании. Сначала проверьте вручную, затем сравните с обычной автоматизацией.', 'Reconcile orders, costs and source records for one campaign. Verify manually first, then compare with conventional automation.');
    metrics = t('წყაროთი მონიშნული შეკვეთების წილი, უცნობი წყაროს წილი, დაბრუნებები და ანგარიშის მომზადების დრო.', 'Доля заказов с источником, доля неизвестных источников, возвраты и время подготовки отчёта.', 'Share of orders with a source, unknown-source share, returns and report preparation time.');
    caution = t('ბმული ან პრომოკოდი ყველა შეძენას ვერ აღრიცხავს და დამატებით გამოწვეულ გაყიდვას თავისთავად არ ამტკიცებს. AI დაკარგულ წყაროს სანდოდ ვერ აღადგენს.', 'Ссылка или промокод не охватывают все покупки и сами по себе не доказывают дополнительные продажи. AI не сможет достоверно восстановить отсутствующий источник.', 'A link or promo code does not cover every purchase or prove incremental sales. AI cannot reliably reconstruct an unrecorded source.');
  } else if (s.focus === 'growth') {
    const bottleneck = val(s, 'bottleneck');
    diagnosis = ['reach', 'enquiries'].includes(bottleneck)
      ? t('თქვენი პასუხი ყურადღებას შეთავაზების ნახვიდან მომართვამდე ეტაპზე ამახვილებს. მხოლოდ შეტყობინებების ავტომატიზაციის სარგებელი ჯერ არ დასტურდება.', 'Ваш ответ указывает на этап от просмотра предложения до обращения. Польза одной лишь автоматизации сообщений пока не подтверждена.', 'Your answer points to the path from seeing an offer to making an enquiry. The benefit of message automation alone is not established.')
      : bottleneck === 'conversion' ? t('თქვენ აღწერთ მომართვიდან შეძენამდე სირთულეს. მიზეზი უნდა გადამოწმდეს უარის რეალური მაგალითებით.', 'Вы описываете проблему перехода от обращения к покупке. Причину нужно проверить на реальных примерах отказа.', 'You describe difficulty converting enquiries into purchases. The cause needs checking against actual rejection examples.') : '';
    next = bottleneck === 'conversion'
      ? t('ერთი ჩვეულებრივი პერიოდის მომართვები და შეძენები შეადარეთ; უარის მიზეზები ცალკე ჩაიწერეთ. შემდეგ შეამოწმეთ ერთი ცვლილება შეთავაზებაში ან პასუხის პროცესში.', 'За один обычный период сопоставьте обращения и покупки, запишите причины отказа. Затем проверьте одно изменение предложения или обработки обращения.', 'Compare enquiries and purchases for one typical period and record rejection reasons. Then test one change to the offer or response process.')
      : t('ერთ არხში ცალ-ცალკე გაზომეთ შეთავაზების ნახვა, მომართვა და შეძენა. შედეგით გადაწყვიტეთ, რომელ ეტაპზეა საჭირო ცვლილება.', 'В одном канале отдельно измерьте просмотры предложения, обращения и покупки. По результату определите этап, требующий изменения.', 'In one channel, measure offer views, enquiries and purchases separately. Identify the stage that needs improvement.');
    metrics = t('ნახვა → მომართვა → შეძენა; რაოდენობა თითოეულ ეტაპზე და უარის მიზეზი.', 'Просмотр → обращение → покупка; количество на каждом этапе и причины отказа.', 'View → enquiry → purchase; counts at each stage and rejection reasons.');
  } else if (s.focus === 'chats') {
    next = t('ტესტი შემოსაზღვრეთ ერთი არხით და ერთი განმეორებადი ამოცანით. რთული შემთხვევა ადამიანს გადაეცეს; დაწყებამდე გაზომეთ არსებული შედეგი.', 'Ограничьте тест одним каналом и одной повторяемой задачей. Сложные случаи передавайте человеку; до старта измерьте исходный результат.', 'Limit the test to one channel and one repeated task. Escalate complex cases to a person and measure the baseline first.');
    metrics = t('პასუხის დრო, უპასუხო მომართვა, ადამიანის ჩარევა, შეცდომა და დასრულებული ჩაწერა ან შეკვეთა.', 'Время ответа, пропущенные обращения, передачи человеку, ошибки и завершённые записи или заказы.', 'Response time, missed enquiries, human handoffs, errors and completed bookings or orders.');
  } else if (s.focus === 'calls') {
    diagnosis = ['cold', 'unclear'].includes(val(s, 'call_permission'))
      ? t('ზარის მიმღებთა კავშირი და თანხმობის გზა ჯერ არ იძლევა უსაფრთხო პილოტის საფუძველს.', 'Связь с получателями звонков и путь согласия пока не дают основания для безопасного пилота.', 'The relationship to call recipients and consent path do not yet support a safe pilot.') : '';
    next = t('შემოიფარგლეთ საკუთარი კლიენტების ერთი განმეორებადი სცენარით, მაგალითად ჩაწერის დადასტურებით. არასტანდარტული კითხვა გადაეცეს ადამიანს; ზარის დაწყებამდე შეამოწმეთ disclosure და consent.', 'Ограничьте проверку одним повторяющимся сценарием для собственных клиентов, например подтверждением записи. Нестандартный вопрос передавайте человеку; до запуска проверьте disclosure и consent.', 'Limit the test to one repeated scenario for the company’s own customers, such as booking confirmation. Escalate unusual questions to a person and check disclosure and consent before launch.');
    metrics = t('დასრულებული ზარი, დადასტურება ან გადაჯავშნა, ადამიანის მოთხოვნა, შეცდომა და ხელით დახარჯული დრო.', 'Завершённый звонок, подтверждение или перенос, запрос человека, ошибки и ручное время.', 'Completed calls, confirmations or reschedules, human requests, errors and manual time.');
  } else if (s.focus === 'content') {
    next = t('ერთი ფორმატის მცირე ნიმუში შეადარეთ არსებულ წარმოებას; ბრენდის შესაბამისობა გამოქვეყნებამდე ადამიანმა შეამოწმოს.', 'Сравните небольшую выборку одного формата с текущим производством; соответствие бренду проверяет человек до публикации.', 'Compare a small sample of one format with current production; a person should approve brand suitability before publishing.');
    metrics = t('მომზადების დრო, დამტკიცებული მასალების წილი, შესწორებები და ხარჯი.', 'Время производства, доля одобренных материалов, правки и затраты.', 'Production time, approval rate, revisions and cost.');
  } else if (s.focus === 'docs') {
    next = t('ერთი ტიპის არასენსიტიურ დოკუმენტებზე შეადარეთ შედეგი ადამიანის მიერ შემოწმებულ ნიმუშს. საბოლოო გადაწყვეტილება ადამიანმა მიიღოს.', 'На несекретной выборке одного типа документов сравните результат с проверенным человеком эталоном. Окончательное решение оставьте человеку.', 'Compare a non-sensitive sample of one document type against a human-reviewed reference. Keep final decisions with a person.');
    metrics = t('დამუშავების დრო, გამოტოვებული ველები, არასწორი მონაცემები და ხელით შესწორება.', 'Время обработки, пропущенные поля, неверные данные и ручные исправления.', 'Processing time, missing fields, incorrect data and manual corrections.');
  } else if (s.focus === 'ads') {
    next = t('ერთი კამპანიის ფარგლებში შეამოწმეთ შეძენის აღრიცხვა და ერთი განმეორებადი ოპერაცია. ბიუჯეტის ცვლილება ადამიანმა დაამტკიცოს.', 'На одной кампании проверьте учёт покупок и одну повторяемую операцию. Изменения бюджета утверждает человек.', 'Check purchase measurement and one repeated operation on a single campaign. A person approves budget changes.');
    metrics = t('დადასტურებული კონვერსიები, ხარჯი, შეცდომები და ანალიზის დრო.', 'Подтверждённые конверсии, затраты, ошибки и время анализа.', 'Verified conversions, spend, errors and analysis time.');
  } else if (s.focus === 'web') {
    next = t('აირჩიეთ ერთი მომხმარებლის მოქმედება საიტზე და ხელით დაადასტურეთ, სად ჩერდება გზა. ჯერ შეამოწმეთ მარტივი UX/ინფორმაციის ცვლილება, შემდეგ — მცირე web pilot.', 'Выберите одно действие клиента на сайте и вручную подтвердите, где обрывается путь. Сначала проверьте простое изменение UX/информации, затем — небольшой web pilot.', 'Choose one customer action on the site and manually confirm where the journey stops. Test a simple UX/information change first, then a small web pilot.');
    metrics = t('მოქმედების დასრულების წილი, მომართვები, შეცდომა, დრო და ხელით ჩარევა.', 'Доля завершённых действий, обращения, ошибки, время и ручные вмешательства.', 'Action completion rate, enquiries, errors, time and manual interventions.');
  } else if (s.focus === 'office') {
    next = t('აირჩიეთ ერთი შიდა პროცესი და დახაზეთ მისი რეალური ნაბიჯები სისტემებს შორის. პილოტი არ უნდა შეეხოს შეუმოწმებელ გადაწყვეტილებას ადამიანის დამტკიცების გარეშე.', 'Выберите один внутренний процесс и зафиксируйте реальные шаги между системами. Пилот не должен затрагивать непроверенное решение без утверждения человеком.', 'Choose one internal process and map its actual steps between systems. A pilot must not affect an unreviewed decision without human approval.');
    metrics = t('დამუშავების დრო, ხელით გადატანები, შეცდომა, შეჩერებული შემთხვევები და approval-ის დრო.', 'Время обработки, ручные переносы, ошибки, зависшие случаи и время согласования.', 'Processing time, manual transfers, errors, stalled cases and approval time.');
  } else if (s.focus === 'app') {
    next = t('შემდეგი ნაბიჯი არის მოკლე scoping: მომხმარებელი, ერთი სამუშაო trajectory, მონაცემის წყარო, წარმატების საზომი და ჩარევის ზღვარი. ჯერ არ არის build-ის დაპირება.', 'Следующий шаг — короткий scoping: пользователь, одна рабочая траектория, источник данных, метрика успеха и граница вмешательства. Это ещё не обещание разработки.', 'Next is a short scoping: user, one workflow trajectory, data source, success measure and intervention boundary. It is not yet a build promise.');
    metrics = t('ერთი შეთანხმებული workflow, ხელით შესრულების დრო, შეცდომა და მიღებული შედეგის ხარისხი.', 'Один согласованный workflow, ручное время, ошибки и качество результата.', 'One agreed workflow, manual time, errors and outcome quality.');
  } else if (s.focus === 'rescue') {
    next = t('შეაგროვეთ არსებული აპლიკაციის აღწერა, საჯარო URL ან უსაფრთხო read-only მასალა და განმეორებადი წარუმატებლობის მაგალითები. პაროლები, API-გასაღებები და production მონაცემები არ გამოგზავნოთ.', 'Соберите описание существующего приложения, публичный URL или безопасные read-only материалы и примеры повторяющихся сбоев. Не отправляйте пароли, API-ключи или production-данные.', 'Collect a description of the existing app, a public URL or safe read-only materials, and examples of repeat failures. Do not send passwords, API keys or production data.');
    metrics = t('განმეორებადი failure, აღდგენის დრო, დაზარალებული workflow და შემოწმებული findings.', 'Повторяющиеся сбои, время восстановления, затронутый workflow и проверенные findings.', 'Repeated failures, recovery time, affected workflows and verified findings.');
  } else if (s.focus === 'staff') {
    next = t('გამოკვეთეთ ერთი ცოცხალი მომსახურების როლი, მისი სამუშაო საათები, ტიპური შემთხვევები და ხარისხის შემოწმების წესი. ეს არ არის ავტომატური ჩატის პილოტი.', 'Опишите одну роль живого сервиса, часы работы, типовые случаи и правило проверки качества. Это не пилот автоматического чата.', 'Define one live-service role, working hours, typical cases and quality-review rule. This is not an automated-chat pilot.');
    metrics = t('დახურული შემთხვევები, პასუხის დრო, ხარისხის შემოწმება და კლიენტის გადაცემა.', 'Закрытые случаи, время ответа, проверка качества и передачи клиенту.', 'Closed cases, response time, quality review and customer handoffs.');
  }
  if (s.focus === 'chats' && usable(s, 'baseline')) {
    next = t('შემოიფარგლეთ ერთი არხით და განმეორებადი კითხვებით. შედეგი შეადარეთ თქვენ მიერ დასახელებულ საწყის მაჩვენებელს იმავე პერიოდში და იმავე ტიპის მომართვებისთვის. რთული საკითხი ადამიანს გადაეცეს.', 'Ограничьте проверку одним каналом и повторяющимися вопросами. Сравните результат с указанным вами исходным показателем для того же периода и типа обращений. Сложные вопросы передавайте человеку.', 'Limit the test to one channel and repeated questions. Compare with your stated baseline for the same period and enquiry type. Hand complex questions to a person.');
  }
  if (s.focus === 'growth' && ['reach', 'enquiries'].includes(val(s, 'bottleneck'))) {
    next = t('შემდეგი 7 დღის განმავლობაში ერთ არხში ჩაიწერეთ თითოეული პოსტის ნახვა, მიღებული მომართვა და შეძენა. თუ ნახვა ცოტაა, შეამოწმეთ გავრცელების ერთი ახალი გზა. თუ ნახვა არის და მომართვა ცოტაა, შეცვალეთ ერთი შეთავაზება ან მოწოდება. ერთდროულად მხოლოდ ერთი ცვლილება შეამოწმეთ.', 'В течение следующих 7 дней в одном канале записывайте просмотры каждой публикации, обращения и покупки. Если просмотров мало — проверьте один новый способ распространения. Если просмотры есть, а обращений мало — измените одно предложение или призыв. Проверяйте по одному изменению за раз.', 'For the next 7 days, record each post’s views, enquiries and purchases in one channel. If views are low, test one new distribution method. If views exist but enquiries are low, change one offer or call to action. Test one change at a time.');
  }
  if (s.focus === 'growth' && /B2B|консалт|consult|კონსალტ/iu.test(val(s, 'business'))) {
    metrics = t('მომართვა, შეხვედრა, გაგზავნილი შეთავაზება, მიღებული პასუხი და შეთანხმება; უარის მიზეზი ცალკე ჩაიწერეთ.', 'Обращения, встречи, отправленные предложения, полученные ответы и сделки; отдельно записывайте причины отказа.', 'Enquiries, meetings, proposals sent, replies and deals; record rejection reasons separately.');
  }
  if (a.verdict === 'insufficient' || (a.verdict === 'process_first' && !['growth', 'attribution'].includes(s.focus))) {
    next = t('აირჩიეთ ერთი რეალური შემთხვევა და ჩაიწერეთ: რა მოხდა, სად შეფერხდა საქმე და როგორ დასრულდა. ჯერ შეამოწმეთ პროცესის მარტივი ცვლილება; ამ მონაცემებით ხელახლა შეაფასეთ AI-ის საჭიროება.', 'Разберите один реальный случай: что произошло, на каком шаге возникла задержка и чем всё закончилось. Проверьте простое изменение процесса и по этим данным повторно оцените необходимость AI.', 'Review one actual case: what happened, where it stalled and how it ended. Test a simple process change and use that evidence to reassess the need for AI.');
    metrics = t('შემთხვევის შედეგი, შეფერხების მიზეზი და დახარჯული დრო.', 'Исход случая, причина задержки и затраченное время.', 'Case outcome, cause of delay and time spent.');
  }
  if (a.verdict === 'not_now') next = t('ჯერ ახალი სისტემა არ შეიძინოთ. ჩაიწერეთ შემდეგი წარუმატებელი შემთხვევის მიზეზი და ხელახლა შეაფასეთ პროცესი, თუ დატვირთვა ან დანაკარგი გაიზრდება.', 'Пока не покупайте новую систему. Запишите причину следующего неудачного случая и вернитесь к оценке, если нагрузка или потери увеличатся.', 'Do not buy a new system now. Record the cause of the next unsuccessful case and reassess if workload or losses increase.');
  if (a.product && a.verdict === 'pilot') next += ' ' + t('შემოთავაზებული სატესტო პერიოდი: 14 დღე. გაგრძელება მხოლოდ მაშინ, თუ დრო მცირდება და შეცდომების დონე არ უარესდება; სერიოზული შეცდომისას ტესტი შეჩერდეს.', 'Предлагаемый срок проверки: 14 дней. Продолжать, если время сокращается без ухудшения качества; при серьёзной ошибке остановить тест.', 'Proposed test duration: 14 days. Continue if time decreases without worse quality; stop the test on a serious error.');
  const gaps = requiredFields(s).filter((f) => !usable(s, f));
  const reference = (field: Field, label: string) => usable(s, field) ? `${label}: [${s.facts[field]!.id}] “${s.facts[field]!.quote}”` : '';
  const actionContext = [
    reference('pain', t('რა უნდა შეიცვალოს', 'Что должно измениться', 'What needs to change')),
    reference('impact', t('რატომ არის ეს მნიშვნელოვანი', 'Почему это важно', 'Why it matters')),
    reference('baseline', t('შედარების საწყისი მაჩვენებელი', 'С чем сравнивать результат', 'Baseline to compare against')),
    a.product ? reference('constraints', t('ადამიანის კონტროლი', 'Граница ответственности человека', 'Human control boundary')) : '',
    a.product ? reference('owner', t('ვინ შეამოწმებს შედეგს', 'Кто проверяет результат', 'Who reviews the result')) : '',
    a.verdict === 'pilot' ? reference('repetition', t('რა შედის პირველ შემოწმებაში', 'Что включить в первую проверку', 'Scope of the first test')) : '',
  ].filter(Boolean).join('\n\n');
  const channelText = [s.facts.channels?.quote, s.facts.process?.quote, s.facts.systems?.quote].filter(Boolean).join(' ');
  const channel = s.focus === 'chats' ? channelText.match(/WhatsApp|Instagram|Telegram|Messenger/i)?.[0] : null;
  if (channel && a.verdict === 'pilot') next = t(`შემოთავაზებული პირველი არხი: ${channel}. `, `Предлагаемый первый канал: ${channel}. `, `Proposed first channel: ${channel}. `) + next;
  const sections = [
    'aiAUDIT · Quick Audit',
    t('რა შევისწავლეთ — თქვენი მიზანი და ბიზნესი', 'Что исследовали — ваш бизнес и цель', 'Scope — your business and goal'), evidence(['business', 'objective']),
    t('დასკვნა', 'Вывод', 'Conclusion'), findings[a.verdict], diagnosis,
    actionContext,
    `${t('AI შესაძლებლობა', 'Возможность AI', 'AI opportunity')}: ${a.opportunity === 'supported' ? t('დასაბუთებულია ტესტისთვის', 'Обоснована для проверки', 'Supported for testing') : t('დასადასტურებელია', 'Требует подтверждения', 'Needs confirmation')}. ${t('მზადყოფნა', 'Готовность', 'Readiness')}: ${a.readiness === 'ready' ? t('პასუხებით დასტურდება; ინტეგრაცია შესამოწმებელია', 'Подтверждена ответами; интеграцию нужно проверить', 'Supported by answers; integration needs verification') : t('შეზღუდულია ან უცნობია', 'Ограниченная или неизвестная', 'Limited or unknown')}.`,
    `${t('რეკომენდაცია', 'Рекомендация', 'Recommendation')}: ${a.product ? `${PRODUCT_CATALOG[a.product].name[language]} — ${a.verdict === 'pilot' ? t('მცირე პილოტი, ეფექტის გარანტიის გარეშე', 'небольшой пилот без гарантии эффекта', 'a small pilot without a guaranteed outcome') : PRODUCT_CATALOG[a.product].purpose[language]}` : t('ამ ეტაპზე iAI პროდუქტის შეძენას არ გირჩევთ.', 'На этом этапе покупку продукта iAI не рекомендуем.', 'We do not recommend purchasing an iAI product at this stage.')}`,
    t('შემდეგი ნაბიჯი / შემოთავაზებული შემოწმება', 'Следующий шаг / предлагаемая проверка', 'Next step / proposed test'), next,
    t('რა გავზომოთ', 'Что измерить', 'What to measure'), metrics,
    t('როდის გავაგრძელოთ', 'Как принять решение по результату', 'How to decide after the test'),
    a.verdict === 'pilot' ? t('შეადარეთ ერთნაირი სამუშაო და პერიოდი. გააგრძელეთ მხოლოდ მაშინ, თუ შედეგი უმჯობესდება, შეცდომები არ მატულობს და შემმოწმებელი ამას ადასტურებს.', 'Сравнивайте одинаковые задачи и периоды. Продолжайте, если целевой показатель улучшается без роста ошибок и ответственный подтверждает качество.', 'Compare equivalent tasks and periods. Continue only if the target measure improves without more errors and the reviewer confirms quality.') : t('თუ მიზეზი ჯერ უცნობია, ჯერ მონაცემები შეაგროვეთ. AI განიხილეთ მხოლოდ მაშინ, როცა განმეორებადი პრობლემა და მისი გავლენა დადასტურდება.', 'Если причина пока неизвестна, сначала соберите данные. Рассматривайте AI, когда подтвердятся повторяемая проблема и её влияние.', 'If the cause remains unknown, gather evidence first. Consider AI once a repeatable problem and its impact are established.'),
    t('რა დაგჭირდებათ', 'Что потребуется', 'Requirements'), t('რეალური მაგალითები, მონაცემებზე ნებადართული წვდომა და შემმოწმებელი ადამიანი. კონკრეტული ინტეგრაციის შესაძლებლობა ცალკე შესამოწმებელია.', 'Реальные примеры, разрешённый доступ к данным и человек для проверки. Возможность конкретной интеграции проверяется отдельно.', 'Real examples, authorized data access and a human reviewer. Specific integrations require separate verification.'),
    t('რისკი და შეზღუდვა', 'Риски и ограничения', 'Risks and limitations'), caution,
    t('სანდოობა და ინფორმაციის ნაკლებობა', 'Уверенность и пробелы', 'Confidence and gaps'),
    gaps.length ? t('შეზღუდული. უცნობი ან დაუდასტურებელი საკითხები:', 'Ограниченная. Неизвестные или неподтверждённые вопросы:', 'Limited. Unknown or unconfirmed questions:') + '\n' + gaps.map((f) => `• ${BANK[f].text[language]}${s.facts[f]?.status === 'contradicted' ? t(' — პასუხები ერთმანეთს ეწინააღმდეგება', ' — противоречивые ответы', ' — conflicting answers') : ''}`).join('\n') : t('საშუალო: დასკვნა ეყრდნობა თქვენს პასუხებს; დამოუკიდებელი გაზომვა არ ჩატარებულა.', 'Средняя: вывод основан на ваших ответах; независимых измерений не проводилось.', 'Medium: based on your answers; no independent measurements were performed.'),
    t('რას არ გირჩევთ ახლა', 'Что сейчас не рекомендуем', 'Not recommended now'),
    t('სხვა პროდუქტებისთვის ამ საუბარში საკმარისი საფუძველი არ შეგვიგროვებია. გაყიდვების ზრდა ან ფინანსური ROI არ გამოგვითვლია.', 'Для остальных продуктов в этом разговоре недостаточно оснований. Рост продаж и финансовый ROI не рассчитывались.', 'This conversation does not establish sufficient evidence for other products. Sales growth and financial ROI were not calculated.'),
    t('მტკიცებულება — თქვენი სიტყვები', 'Основания — ваши слова', 'Evidence — your words'), evidence(a.evidence.filter((f) => !['business', 'objective', 'priority_check', 'pain', 'impact', 'baseline', ...(a.product ? ['constraints', 'owner'] : [])].includes(f))),
    t('შეგიძლიათ შეასწოროთ ნებისმიერი ფაქტი — ანგარიში თავიდან შეფასდება.', 'Любой факт можно исправить — вывод будет пересмотрен.', 'You can correct any fact — the conclusion will be reassessed.'),
  ];
  return sections.filter(Boolean).join('\n\n');
}
